name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: List files in build folder
        run: ls -la ./dist  # Verifikasi apakah build menghasilkan file yang benar

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact  # Nama artifact yang digunakan untuk upload
          path: ./build          # Pastikan path yang di-upload benar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact  # Pastikan nama artifact konsisten
          path: ./build

      - name: List files in dist folder
        run: ls -la ./dist  # Verifikasi apakah artifact sudah didownload

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
